### PR TITLE
Add distDir to defaultConfig

### PR DESCRIPTION
**Pull request by broerse**
Make it possible to change the distDir in an other plug-in like this:

```
      willDeploy: function(context) {
        var distDir = this.readConfig('distDir');
        return {
          distDir: distDir + path.sep + '_attachments'
        };
      },


```

### CODE REVIEW

**Comment by lukemelia** [comment]
Hi @broerse, I don't fully understand the usecase, so what I'm about to suggest may not work, but it will be helpful to me if you explain why it won't. Could you configure the build plugin's outputPath in deploy.js and consume the context.distDir from your plugins (without this PR)? i.e.

```js
// config/deploy.js
return function(deployTarget){
  var ENV = {
    build: 'tmp/dist-deploy/_attachments'
  }
};
```

Then the build plugin will add this to the context as `distDir` and other plugins can read that.

**Comment by broerse** [comment]
Hi @lukemelia,

context settings can be changed by each plug-in as long as they are not in deploy.js. (See: https://github.com/ember-cli/ember-cli-deploy/issues/265#issuecomment-159361934) I like my couchdb plug-in to work out-of-the box. So I don't want to write in some doc anything about the need for setting an `_attachments` folder in some config. 

Without knowledge of coucdb you can now overwrite  https://github.com/ember-cli-deploy/ember-cli-deploy-build#outputpath to `f:\temp` and everything still works.

See the need for `_attachments` : https://github.com/jo/couchdb-compile#attachments

My working code:

```
defaultConfig: {
        filePattern: '**/*.{js,css,png,gif,ico,jpg,map,xml,txt,svg,swf,eot,ttf,woff,woff2}',
        couchDir: function(context) {
          return context.couchDir;
        },
        distDir: function(context) {
          return context.distDir;
        },
        distFiles: function(context) {
          return context.distFiles || [];
        }
      },
      
      willDeploy: function(context) {
        var distDir = this.readConfig('distDir');
        return {
          couchDir: distDir,
          distDir: distDir + path.sep + '_attachments'
        };
      },
```

**Comment by broerse** [comment]
This PR basically creates mutable distDir input for the build hook.

**Comment by broerse** [comment]
First working CouchDB deploy that needs this PR: https://github.com/martinic/ember-cli-deploy-couchdb/blob/master/index.js

**Comment by lukemelia** [comment]
@broerse I'm uncomfortable with this because having outputPath and distDir both as inputs to ember-cli-deploy-build is confusing. Perhaps @duizendnegen @LevelbossMike @achambers or @ghedamat have another opinion or idea?

**Comment by broerse** [comment]
@lukemelia We can keep only `outputPath` but it needs the extra if (See https://github.com/ember-cli-deploy/ember-cli-deploy-build/issues/22)

**Comment by duizendnegen** [comment]
I'm also uncomfortable with both outputPath and distDir - generically I'm uncomfortable with rewriting/overwriting the context object (but on the other hand, this also seems to be a strength of ECD)
I'm not seeing what other `if` would solve this, but reducing information redundancy is almost always a good thing.

**Comment by broerse** [comment]
@duizendnegen Don't know where to add my `if` yet but I imagine the flowing.
- first time readConfig `return context.outputPath || 'tmp' + path.sep + 'deploy-dist';` there is no `context.outputPath` so you get `outputPath` from `deploy.js` or `'tmp' + path.sep + 'deploy-dist'`
- `outputPath` is returned to `context.outputPath` by some plugin. Changed or not.
- next time readConfig `return context.outputPath || 'tmp' + path.sep + 'deploy-dist';` there is now `context.outputPath` so you get `context.outputPath` and not `outputPath` from `deploy.js`

The last step needs the if because it is not how it is now.

**Comment by broerse** [comment]
@duizendnegen It is also the case that if you specify `distDir` in `deploy.js` you now don't get the `distDir` from `ember-cli-deploy-build

**Comment by broerse** [comment]
First deploy with couchdb plug-in:. 

http://localhost:5984/emberapp/_design/deploytest1/_rewrite/

I don't want to use my own ember-cli-deploy-build fork. Can we settle on something?

**Comment by duizendnegen** [comment]
I find it hard to advice on this one - there's information all over the place and I still don't understand the real use case. All I can say is that having no redundant information is essential, so is a reasonable usage of the `context` hash, especially in such an essential plugin as `build`.
If you could give a one-line summary of the need of a seperated dist-dir and output-path, then I might be able to better judge.

**Comment by broerse** [comment]
@duizendnegen @lukemelia Hard to do in one-line ;-) My ember-cli-deploy-couchdb is ready. (It needs some test) `distDir: distDir + path.sep + '_attachments'` is needed to hide complex couchapp stuff from endusers. See:

https://github.com/broerse/ember-cli-deploy-couchdb/blob/master/index.js

**Comment by duizendnegen** [comment]
What _complex stuff_? The attachments? What role does `outputPath` play in here?
Can't you cp the built app in a `didBuild` step?

I see this as a specific use case and I wouldn't be comfortable supporting adding redundancy just because of a copy step.

**Comment by broerse** [comment]
@duizendnegen no you can't cp. You can use move and change the distDir so other hook still know where the build files are. We can change `outputPath` to do this but it will need some change to. See https://github.com/ember-cli-deploy/ember-cli-deploy-build/pull/23#issuecomment-160942184

**Comment by broerse** [comment]
@lukemelia if we change deploy to only overwrite settings with settings from deploy.js as long as they are not in `context` we can change this ember-cli-deploy-build PR to only have one input an one output. I think it is more logical to have `distDir` as input and output but for legacy reasons it can be `outputPath` as input and `distDir` as output.

If we don't change to overwriting settings with settings from deploy.js as long as they are not in `context` this PR is the best way to solve this problem.

**Comment by LevelbossMike** [comment]
Just reading up on this. Why does the couchDb plugin need to modify `context.distDir` directly? can't it just take whatever is specified as distDir and copy it back into the context under a new key if it needs that information? The deployment context was meant to be a way to share information between plugins not to mutate state across a deployment (as this is most likely always a bad idea and will lead to bugs that would be really hard to track down).

**Comment by LevelbossMike** [comment]
I get the idea that it should be easy for users to setup a plugin. What I don't like about this is that this creates the possibility for plugins to basically magically rewrite settings in `config/deploy.js`. I don't think plugins should be allowed to do this as this is already possible with a setting in `deploy.js` (as Luke pointed out). If you want to make it easy for users to get started another idea would be to provide a blueprint for `deploy.js` with this plugin (or most likely in a plugin-pack).

**Comment by broerse** [comment]
@LevelbossMike @lukemelia @duizendnegen My only goal is that [ember-cli-deploy-couchdb](https://github.com/martinic/ember-cli-deploy-couchdb) works out-of-the-box. I can copy it under a new temp dir and use that. The problem is that other plug-ins that work with `distDir` don't know what the current `distDir` is. If every plug-in needs to copy `distDir` to make deploy work this seems to work against a deploy pipeline.  I like the help and feedback but if everybody helping here thinks my issues are not valid I can release something like this PR as `ember-cli-delpoy-build-configurable` and get [ember-cli-deploy-couchdb](https://github.com/martinic/ember-cli-deploy-couchdb) released.

**Comment by duizendnegen** [comment]
Releasing `ember-cli-deploy-build-plus` or providing docs for end users to configure `deploy.js` appropriately (the latter being my recommendation) is the approach I would advice.

We realise that the `context` hash and the configurations are still prone to change, and will take the learnings from this issue with us when focusing on a more robust way of sharing information between plugins.

Closing this now, feel free to re-open a ticket if there are other issues.

**Comment by broerse** [comment]
I will go for `ember-cli-deploy-build-plus` until we have a robust way of sharing information. I will deprecate `ember-cli-deploy-build-plus` as my issue is tackled. Thanks for all input!

**Comment by lukemelia** [comment]
Good luck, @broerse. I would seriously consider having your users use the standard build plugin and configure it as needed. Presumably they will already need to configure information about their couchdb collection. If it's in the same docs, it doesn't seem like too much of a burden.

**Comment by broerse** [comment]
@lukemelia Thanks. Exactly my point. I will try to keep my `ember-cli-deploy-build-plus` up-to-date until this is solved.

**Comment by broerse** [comment]
Never published to NPM but it seems to work ;-)

https://www.npmjs.com/package/ember-cli-deploy-build-plus

**Comment by broerse** [comment]
@duizendnegen released [v0.1.3](https://www.npmjs.com/package/ember-cli-deploy-build-plus). It can also build an ENV specific robots.txt file.

**Pull request closed without merging**
