### PR TITLE
include hidden files in distFiles

### PR DESCRIPTION
**Pull request by bevinhex**
## What Changed & Why
dot files are ignored from glob.sync , files like .htaccess would not gets deployed since distFiles do not include hidden files.

## Related issues
#29 

## People
@lukemelia

### CODE REVIEW

**Comment by sukima** [comment]
Just spent an hour looking into this problem! When is this going to merge?

**Comment by sukima** [comment]
Is there a workaround?!

**Comment by sukima** [comment]
For anyone who comes across this (if they do as I had to search GitHub for 30 minutes to find this PR) here is how I worked around this in my ember apps prior to this PR:

Run `ember generate in-repo-addon ember-cli-deploy-dotfiles`.

### `lib/ember-cli-deploy-dotfiles/package.json`

```js
{
  "name": "ember-cli-deploy-dotfiles",
  "keywords": [
    "ember-addon",
    "ember-cli-deploy-plugin"
  ]
}
```

### `lib/ember-cli-deploy-dottfiles/index.js`

```js
'use strict';

module.exports = {
  name: require('./package').name,

  createDeployPlugin: function(options) {
    return {
      name: options.name,

      didBuild: function(context) {
        var config = context.config.dotfiles || {};
        var distFiles = config.includeMissingFiles || [];
        return { distFiles: distFiles };
      }
    };
  }
};
```

Then simply add the following to your `config/deploy.js`:

```js
  var ENV = {
    build: {},
    // include other plugin configuration that applies to all deploy targets here
    'dotfiles': {
      includeMissingFiles: ['.htaccess']
    }
  };
```

**Comment by lukemelia** [comment]
@sukima apologies for the long delay on this, and thanks for documenting your workaround.

@achambers @ghedamat I'm worried this has some potential to be a breaking change at this point. I'm inclined to agree it should be the default though. Major version bump? Also, seems like this should be doc'd and/or configurable. What do you guys think?

**Comment by achambers** [comment]
@lukemelia said:

> @achambers @ghedamat I'm worried this has some potential to be a breaking change at this point. I'm inclined to agree it should be the default though. Major version bump? Also, seems like this should be doc'd and/or configurable. What do you guys think?

Yeh, it does seem like it could be problematic. So, major version bump is, I guess, the way to indicate this. And yeh, a configuration option to enable/disable the `dot` property would make sense.

In hindsight, I think I regret this `distFiles` idea now. It doesn't really add any value and maybe I should have just left it up to each plugin to look in the dist dir for the files they want. 🤷‍♀️

**Comment by bevinhex** [comment]
> Just spent an hour looking into this problem! When is this going to merge?

At the moment, I'm using https://www.npmjs.com/package/patch-package , so make the changes to the node_module as in the PR, then create a patch.

**Comment by lukemelia** [comment]
Thanks everyone especially @bevinhex and @sukima. I'm planning to merge this as part of https://github.com/ember-cli-deploy/ember-cli-deploy-build/pull/55

**Pull request closed without merging**
